# Generated by Django 4.2.13 on 2024-06-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KwentasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=4)),
            ],
        ),
    ]
