# Generated by Django 4.2.13 on 2024-06-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KwentasApp', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
