# Generated by Django 4.0.1 on 2024-09-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('KwentasApp', '0003_delete_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('ppa', models.CharField(max_length=255)),
                ('implementing_unit', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('appropriation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remarks', models.TextField()),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilization_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
