# Generated by Django 4.0.1 on 2024-09-14 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0017_alter_requestevent_datetime'),
        ('KwentasApp', '0006_firebaseentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCRUDEvent',
            fields=[
                ('crudevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='easyaudit.crudevent')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
            ],
            bases=('easyaudit.crudevent',),
        ),
    ]
