# Generated by Django 4.0.1 on 2024-09-14 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KwentasApp', '0007_customcrudevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomCRUDEvent',
        ),
    ]
